### ISSUE TITLE
Editing bot_brain.brn

### ISSUE THREAD

**Issue by ghost** [sohelamin/chatbot#1]
Hello Sohelamin,

Is there anyway to edit bot_brain so that it remembers what you have said, because currently if I restart the application, it forgets everything I have taught it.

Thanks in advance,

James Gallagher

**Comment by sohelamin** [comment]
You can delete the bot_brain.brn file and restart the application or we can gitignore the file also so on every installation time it will generate a new file.

**Comment by ghost** [comment]
If I delete bot_brain.brn, the program doesn't answer any questions. -

"amesMacbookAir:chatbot James$ python main-raw.py 
WARNING: No match found for input: load aiml b

Kernel bootstrap completed in 0.01 seconds
Saving brain to bot_brain.brn... done (0.00 seconds)
Enter your message to the bot: Hello
WARNING: No match found for input: Hello

Enter your message to the bot:"

Have any ideas on how to fix it?

**Comment by sohelamin** [comment]
Fixed at 93e823c
