### ISSUE TITLE
asking for help!!!

### ISSUE THREAD

**Issue by YICONGISME** [sohelamin/chatbot#12]
hello, Mr.sohelamin, i need your help. i am your loyal fans. i want to ask you question about "chatbot".
i installed  flask, then i can't  execute the command "pip install -r requriments.txr" , can you help me ? thanks

**Comment by YeonGuKang** [comment]
Pip must be installed before using pip . Did you install it?

**Comment by SoYooooon** [comment]
https://www.youtube.com/watch?v=zPMr0lEMqpo
Please check this video! (about installing pip..)
